/**
 * Real Estate Website - Contact Page
 * Contact form validation and submission
 * Generated by AI on 2023-11-15
 */

document.addEventListener('DOMContentLoaded', function() {
  // Only run on contact page
  if (!document.querySelector('#contact-form')) return;
  
  // Initialize contact form
  initContactForm();
  
  // Initialize map (stub - replace with real API key)
  initMap(24.8607, 67.0011); // Default to Karachi coordinates
});

/**
 * Initialize contact form with validation
 */
function initContactForm() {
  const form = document.querySelector('#contact-form');
  if (!form) return;
  
  form.addEventListener('submit', function(e) {
    e.preventDefault();
    
    // Get form values
    const name = form.querySelector('#name').value.trim();
    const email = form.querySelector('#email').value.trim();
    const phone = form.querySelector('#phone').value.trim();
    const subject = form.querySelector('#subject').value.trim();
    const message = form.querySelector('#message').value.trim();
    
    // Validate form
    if (!name || !email || !message) {
      showAlert('Please fill in all required fields.', 'error');
      return;
    }
    
    if (!/^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/.test(email)) {
      showAlert('Please enter a valid email address.', 'error');
      return;
    }
    
    if (phone && !/^[\d\s\-()+]{10,20}$/.test(phone)) {
      showAlert('Please enter a valid phone number.', 'error');
      return;
    }
    
    // Simulate form submission
    const formData = {
      name,
      email,
      phone: phone || 'Not provided',
      subject: subject || 'No subject',
      message
    };
    
    console.log('Form submitted:', formData); // For demonstration
    
    // Show success message
    showAlert('Thank you for your message. We will get back to you soon!', 'success');
    form.reset();
  });
}

/**
 * Show alert message
 */
function showAlert(message, type = 'success') {
  const alert = document.createElement('div');
  alert.className = `alert alert-${type}`;
  alert.innerHTML = `
    <i class="fas fa-${type === 'success' ? 'check-circle' : 'exclamation-circle'}"></i>
    <div>${message}</div>
  `;
  
  // Add to page
  const container = document.querySelector('.container') || document.body;
  container.prepend(alert);
  
  // Remove after 5 seconds
  setTimeout(() => {
    alert.classList.add('fade-out');
    setTimeout(() => alert.remove(), 300);
  }, 5000);
}

/**
 * Initialize map (stub - replace with real Google Maps API)
 */
function initMap(lat, lng) {
  const mapContainer = document.querySelector('.map-container');
  if (!mapContainer) return;
  
  // This is a placeholder - replace with actual Google Maps API code
  mapContainer.innerHTML = `
    <div class="map-placeholder">
      <i class="fas fa-map-marked-alt"></i>
      <p>Map would display here with API key</p>
      <small>Lat: ${lat}, Lng: ${lng}</small>
    </div>
  `;
  
  // To implement real Google Maps:
  // 1. Include Google Maps API script in your HTML
  // 2. Replace this function with:
  /*
  function initMap(lat, lng) {
    const mapContainer = document.querySelector('.map-container');
    if (!mapContainer) return;
    
    const location = { lat: parseFloat(lat), lng: parseFloat(lng) };
    const map = new google.maps.Map(mapContainer, {
      zoom: 15,
      center: location,
      styles: [
        // Add your custom map styles here
      ]
    });
    
    new google.maps.Marker({
      position: location,
      map: map,
      title: 'Our Office'
    });
  }
  */
}