/**
 * Real Estate Website - Dummy Data
 * Sample property data in JSON format
 * Generated by AI on 2023-11-15
 */

const PROPERTIES = [
  {
    id: "prop-001",
    title: "Luxury Villa in Clifton",
    price: 1200000,
    currency: "USD",
    location: {
      city: "Karachi",
      area: "Clifton",
      address: "12 Sea View Road",
      lat: 24.8099,
      lng: 67.0299
    },
    type: "Villa",
    bedrooms: 5,
    bathrooms: 6,
    area_sqft: 6500,
    year_built: 2018,
    images: [
      "assets/images/prop-001-1.jpg",
      "assets/images/prop-001-2.jpg",
      "assets/images/prop-001-3.jpg",
      "assets/images/prop-001-4.jpg",
      "assets/images/prop-001-5.jpg"
    ],
    features: ["Swimming Pool", "Home Theater", "Gym", "Garden", "Garage", "Security System", "Smart Home"],
    description: "This stunning luxury villa in the heart of Clifton offers breathtaking sea views and unparalleled amenities. The property features a grand entrance, spacious living areas, a modern kitchen with high-end appliances, and a master suite with a private balcony. The outdoor area includes a large swimming pool, landscaped gardens, and ample space for entertainment.",
    agent: {
      name: "Sarah Johnson",
      phone: "+1 (555) 123-4567",
      email: "sarah@luxuryestates.com",
      bio: "Specializing in high-end properties for over 15 years, Sarah has an exceptional track record of matching clients with their dream homes.",
      image: "assets/images/agent-1.jpg"
    },
    featured: true
  },
  {
    id: "prop-002",
    title: "Modern Apartment in DHA",
    price: 450000,
    currency: "USD",
    location: {
      city: "Karachi",
      area: "DHA Phase 5",
      address: "45 Commercial Lane",
      lat: 24.8275,
      lng: 67.0678
    },
    type: "Apartment",
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 2200,
    year_built: 2020,
    images: [
      "assets/images/prop-002-1.jpg",
      "assets/images/prop-002-2.jpg",
      "assets/images/prop-002-3.jpg",
      "assets/images/prop-002-4.jpg"
    ],
    features: ["Concierge", "Gym", "Parking", "Security", "Balcony"],
    description: "This contemporary apartment in the prestigious DHA neighborhood offers luxury living at its finest. The open-concept design features floor-to-ceiling windows, high-end finishes, and a spacious terrace with city views. Building amenities include 24/7 security, a fitness center, and concierge services.",
    agent: {
      name: "Michael Chen",
      phone: "+1 (555) 987-6543",
      email: "michael@luxuryestates.com",
      bio: "With a background in architecture, Michael brings a unique perspective to finding properties that combine form and function.",
      image: "assets/images/agent-2.jpg"
    },
    featured: true
  },
  {
    id: "prop-003",
    title: "Historic Mansion in Saddar",
    price: 2800000,
    currency: "USD",
    location: {
      city: "Karachi",
      area: "Saddar",
      address: "8 Empress Road",
      lat: 24.8484,
      lng: 67.0283
    },
    type: "Mansion",
    bedrooms: 8,
    bathrooms: 7,
    area_sqft: 12000,
    year_built: 1925,
    images: [
      "assets/images/prop-003-1.jpg",
      "assets/images/prop-003-2.jpg",
      "assets/images/prop-003-3.jpg",
      "assets/images/prop-003-4.jpg",
      "assets/images/prop-003-5.jpg",
      "assets/images/prop-003-6.jpg"
    ],
    features: ["Historical", "Library", "Wine Cellar", "Ballroom", "Garden", "Garage"],
    description: "This meticulously preserved historic mansion offers a rare opportunity to own a piece of Karachi's architectural heritage. The property features original woodwork, stained glass windows, and period details throughout. The expansive grounds include formal gardens, a carriage house, and potential for modern updates while maintaining its historic character.",
    agent: {
      name: "David Wilson",
      phone: "+1 (555) 456-7890",
      email: "david@luxuryestates.com",
      bio: "David specializes in historic properties and has extensive knowledge of preservation techniques and restoration.",
      image: "assets/images/agent-3.jpg"
    },
    featured: true
  },
  {
    id: "prop-004",
    title: "Waterfront Penthouse",
    price: 3200000,
    currency: "USD",
    location: {
      city: "Karachi",
      area: "Clifton",
      address: "1 Beachfront Avenue",
      lat: 24.8123,
      lng: 67.0315
    },
    type: "Penthouse",
    bedrooms: 4,
    bathrooms: 5,
    area_sqft: 4800,
    year_built: 2022,
    images: [
      "assets/images/prop-004-1.jpg",
      "assets/images/prop-004-2.jpg",
      "assets/images/prop-004-3.jpg",
      "assets/images/prop-004-4.jpg"
    ],
    features: ["Ocean View", "Private Elevator", "Terrace", "Smart Home", "Concierge", "Gym"],
    description: "This exquisite penthouse offers panoramic ocean views from every room. The open floor plan features designer finishes, a chef's kitchen, and floor-to-ceiling windows. The expansive terrace includes an outdoor kitchen, infinity pool, and multiple seating areas perfect for entertaining. Building amenities include 24/7 concierge, spa services, and a private beach club.",
    agent: {
      name: "Sarah Johnson",
      phone: "+1 (555) 123-4567",
      email: "sarah@luxuryestates.com",
      bio: "Specializing in high-end properties for over 15 years, Sarah has an exceptional track record of matching clients with their dream homes.",
      image: "assets/images/agent-1.jpg"
    }
  },
  {
    id: "prop-005",
    title: "Golf Course Villa",
    price: 1850000,
    currency: "USD",
    location: {
      city: "Karachi",
      area: "DHA Phase 8",
      address: "72 Fairway Drive",
      lat: 24.8356,
      lng: 67.0421
    },
    type: "Villa",
    bedrooms: 6,
    bathrooms: 6,
    area_sqft: 5800,
    year_built: 2019,
    images: [
      "assets/images/prop-005-1.jpg",
      "assets/images/prop-005-2.jpg",
      "assets/images/prop-005-3.jpg",
      "assets/images/prop-005-4.jpg"
    ],
    features: ["Golf Course View", "Private Pool", "Home Office", "Guest House", "Garden"],
    description: "This magnificent villa sits on the fairway of Karachi's premier golf course. The property features a grand foyer, formal living and dining rooms, a gourmet kitchen, and a luxurious master suite. The outdoor living space includes a resort-style pool, covered patio, and beautifully landscaped gardens. The separate guest house is perfect for visitors or staff.",
    agent: {
      name: "Michael Chen",
      phone: "+1 (555) 987-6543",
      email: "michael@luxuryestates.com",
      bio: "With a background in architecture, Michael brings a unique perspective to finding properties that combine form and function.",
      image: "assets/images/agent-2.jpg"
    }
  },
  {
    id: "prop-006",
    title: "Luxury Loft in CBD",
    price: 750000,
    currency: "USD",
    location: {
      city: "Karachi",
      area: "CBD",
      address: "33 High Street",
      lat: 24.8572,
      lng: 67.0098
    },
    type: "Loft",
    bedrooms: 2,
    bathrooms: 2,
    area_sqft: 2800,
    year_built: 2021,
    images: [
      "assets/images/prop-006-1.jpg",
      "assets/images/prop-006-2.jpg",
      "assets/images/prop-006-3.jpg"
    ],
    features: ["Open Concept", "High Ceilings", "Industrial Design", "Concierge", "Roof Deck"],
    description: "This stunning loft in Karachi's Central Business District combines industrial chic with modern luxury. The open floor plan features exposed brick walls, polished concrete floors, and 14-foot ceilings. The spacious living area flows into a gourmet kitchen with custom cabinetry and high-end appliances. Building amenities include a rooftop deck with skyline views, fitness center, and 24/7 concierge.",
    agent: {
      name: "Emma Rodriguez",
      phone: "+1 (555) 789-0123",
      email: "emma@luxuryestates.com",
      bio: "Emma specializes in urban properties and has an extensive network in the city's luxury real estate market.",
      image: "assets/images/agent-4.jpg"
    }
  },
  {
    id: "prop-007",
    title: "Beachfront Bungalow",
    price: 950000,
    currency: "USD",
    location: {
      city: "Karachi",
      area: "Hawksbay",
      address: "7 Shoreline Road",
      lat: 24.7912,
      lng: 66.9578
    },
    type: "Bungalow",
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 3200,
    year_built: 2017,
    images: [
      "assets/images/prop-007-1.jpg",
      "assets/images/prop-007-2.jpg",
      "assets/images/prop-007-3.jpg",
      "assets/images/prop-007-4.jpg"
    ],
    features: ["Beach Access", "Private Deck", "Outdoor Shower", "Solar Panels", "Garage"],
    description: "This charming beachfront bungalow offers direct access to a pristine sandy beach. The home features an open floor plan with large windows to take in the ocean views, a gourmet kitchen, and a spacious master suite. The expansive deck includes an outdoor dining area, lounge space, and steps leading down to the beach. Eco-friendly features include solar panels and rainwater collection.",
    agent: {
      name: "David Wilson",
      phone: "+1 (555) 456-7890",
      email: "david@luxuryestates.com",
      bio: "David specializes in historic properties and has extensive knowledge of preservation techniques and restoration.",
      image: "assets/images/agent-3.jpg"
    }
  },
  {
    id: "prop-008",
    title: "Gated Community Home",
    price: 680000,
    currency: "USD",
    location: {
      city: "Karachi",
      area: "DHA Phase 6",
      address: "24 Safehaven Lane",
      lat: 24.8219,
      lng: 67.0583
    },
    type: "House",
    bedrooms: 4,
    bathrooms: 3,
    area_sqft: 3800,
    year_built: 2015,
    images: [
      "assets/images/prop-008-1.jpg",
      "assets/images/prop-008-2.jpg",
      "assets/images/prop-008-3.jpg"
    ],
    features: ["Gated Community", "Community Pool", "Playground", "Security", "Garden"],
    description: "This beautiful home in a secure gated community offers peace of mind and luxury living. The property features a spacious floor plan with formal living and dining rooms, a modern kitchen with island seating, and a cozy family room. The backyard includes a covered patio and landscaped garden. Community amenities include a swimming pool, playground, and 24/7 security.",
    agent: {
      name: "Emma Rodriguez",
      phone: "+1 (555) 789-0123",
      email: "emma@luxuryestates.com",
      bio: "Emma specializes in urban properties and has an extensive network in the city's luxury real estate market.",
      image: "assets/images/agent-4.jpg"
    }
  },
  {
    id: "prop-009",
    title: "Luxury Condo with City Views",
    price: 520000,
    currency: "USD",
    location: {
      city: "Karachi",
      area: "Clifton",
      address: "15 Skyline Tower",
      lat: 24.8145,
      lng: 67.0276
    },
    type: "Condo",
    bedrooms: 2,
    bathrooms: 2,
    area_sqft: 1800,
    year_built: 2020,
    images: [
      "assets/images/prop-009-1.jpg",
      "assets/images/prop-009-2.jpg",
      "assets/images/prop-009-3.jpg"
    ],
    features: ["City View", "Concierge", "Gym", "Parking", "Balcony"],
    description: "This luxury condo offers breathtaking city views from its floor-to-ceiling windows. The open-concept design features high-end finishes, a gourmet kitchen with premium appliances, and a spacious master suite with walk-in closet. Building amenities include a fitness center, rooftop terrace, and 24/7 concierge service. Perfect for those seeking a low-maintenance luxury lifestyle.",
    agent: {
      name: "Sarah Johnson",
      phone: "+1 (555) 123-4567",
      email: "sarah@luxuryestates.com",
      bio: "Specializing in high-end properties for over 15 years, Sarah has an exceptional track record of matching clients with their dream homes.",
      image: "assets/images/agent-1.jpg"
    }
  },
  {
    id: "prop-010",
    title: "Executive Townhouse",
    price: 890000,
    currency: "USD",
    location: {
      city: "Karachi",
      area: "DHA Phase 7",
      address: "9 Executive Row",
      lat: 24.8298,
      lng: 67.0512
    },
    type: "Townhouse",
    bedrooms: 5,
    bathrooms: 4,
    area_sqft: 4200,
    year_built: 2018,
    images: [
      "assets/images/prop-010-1.jpg",
      "assets/images/prop-010-2.jpg",
      "assets/images/prop-010-3.jpg",
      "assets/images/prop-010-4.jpg"
    ],
    features: ["Private Garage", "Roof Terrace", "Smart Home", "Walk-in Closets", "Security System"],
    description: "This executive townhouse offers sophisticated living in a prime location. The property features a grand entrance, formal living and dining areas, a gourmet kitchen with butler's pantry, and a luxurious master suite. The rooftop terrace provides stunning views and is perfect for entertaining. Additional features include a private garage and smart home technology throughout.",
    agent: {
      name: "Michael Chen",
      phone: "+1 (555) 987-6543",
      email: "michael@luxuryestates.com",
      bio: "With a background in architecture, Michael brings a unique perspective to finding properties that combine form and function.",
      image: "assets/images/agent-2.jpg"
    }
  },
  {
    id: "prop-011",
    title: "Modern Farmhouse",
    price: 1500000,
    currency: "USD",
    location: {
      city: "Karachi",
      area: "Malir",
      address: "3 Orchard Lane",
      lat: 24.9012,
      lng: 67.1823
    },
    type: "Farmhouse",
    bedrooms: 4,
    bathrooms: 4,
    area_sqft: 5200,
    year_built: 2020,
    images: [
      "assets/images/prop-011-1.jpg",
      "assets/images/prop-011-2.jpg",
      "assets/images/prop-011-3.jpg",
      "assets/images/prop-011-4.jpg"
    ],
    features: ["Orchard", "Pool", "Guest House", "Stable", "Solar Panels"],
    description: "This modern farmhouse combines rustic charm with contemporary luxury. The property features an open floor plan with reclaimed wood beams, a chef's kitchen with farmhouse sink, and a spacious great room with fireplace. The grounds include a swimming pool, fruit orchard, and separate guest house. Perfect for those seeking a peaceful retreat without sacrificing modern comforts.",
    agent: {
      name: "Emma Rodriguez",
      phone: "+1 (555) 789-0123",
      email: "emma@luxuryestates.com",
      bio: "Emma specializes in urban properties and has an extensive network in the city's luxury real estate market.",
      image: "assets/images/agent-4.jpg"
    }
  },
  {
    id: "prop-012",
    title: "Penthouse with Terrace",
    price: 2100000,
    currency: "USD",
    location: {
      city: "Karachi",
      area: "Clifton",
      address: "22 Oceanview Tower",
      lat: 24.8112,
      lng: 67.0301
    },
    type: "Penthouse",
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 3800,
    year_built: 2021,
    images: [
      "assets/images/prop-012-1.jpg",
      "assets/images/prop-012-2.jpg",
      "assets/images/prop-012-3.jpg",
      "assets/images/prop-012-4.jpg"
    ],
    features: ["Panoramic Views", "Private Elevator", "Smart Home", "Wine Cellar", "Concierge"],
    description: "This spectacular penthouse offers 360-degree views of the city and ocean. The residence features an open floor plan with designer finishes, a gourmet kitchen with top-of-the-line appliances, and a luxurious master suite with spa-like bathroom. The expansive terrace includes an outdoor kitchen, dining area, and lounge space with fire pit. Building amenities include a private elevator, concierge service, and rooftop pool.",
    agent: {
      name: "David Wilson",
      phone: "+1 (555) 456-7890",
      email: "david@luxuryestates.com",
      bio: "David specializes in historic properties and has extensive knowledge of preservation techniques and restoration.",
      image: "assets/images/agent-3.jpg"
    }
  }
];

// Additional data for other sections
const TEAM = [
  {
    id: "team-1",
    name: "Sarah Johnson",
    position: "Founder & CEO",
    bio: "With over 20 years in luxury real estate, Sarah has built a reputation for excellence and discretion in high-end property transactions.",
    image: "assets/images/agent-1.jpg"
  },
  {
    id: "team-2",
    name: "Michael Chen",
    position: "Senior Agent",
    bio: "Michael's architectural background gives him unique insight into property potential and renovation opportunities.",
    image: "assets/images/agent-2.jpg"
  },
  {
    id: "team-3",
    name: "David Wilson",
    position: "Historic Properties Specialist",
    bio: "David's passion for historic preservation has made him the go-to expert for heritage properties in the region.",
    image: "assets/images/agent-3.jpg"
  },
  {
    id: "team-4",
    name: "Emma Rodriguez",
    position: "Urban Living Expert",
    bio: "Emma's finger on the pulse of city living helps clients find the perfect urban retreats and investment properties.",
    image: "assets/images/agent-4.jpg"
  }
];

const TESTIMONIALS = [
  {
    id: "test-1",
    content: "Working with Luxury Estates was an exceptional experience. They understood exactly what we were looking for and found us our dream home within weeks.",
    author: "Amina Khan",
    position: "Homeowner"
  },
  {
    id: "test-2",
    content: "As an international investor, I needed an agency I could trust. Their market knowledge and attention to detail made the entire process seamless.",
    author: "James Wilson",
    position: "Investor"
  },
  {
    id: "test-3",
    content: "The team went above and beyond to sell our family home at the best possible price. Their marketing strategy and negotiation skills were impressive.",
    author: "Fatima Ahmed",
    position: "Seller"
  }
];

// Company stats for home page
const COMPANY_STATS = {
  propertiesSold: 1248,
  activeListings: 86,
  happyClients: 932,
  yearsExperience: 15
};